export default {
  pages: [
    'pages/index/index',
    'pages/base/button/index',
    'pages/base/icon/index',
    'pages/layout/divider/index',
    'pages/layout/grid/index',
    'pages/nav/breadcrumb/index',
    'pages/nav/pagination/index',
    'pages/nav/steps/index',
    'pages/record/checkbox/index',
    'pages/record/form/index',
    'pages/record/input/index',
    'pages/record/input-number/index',
    'pages/record/radio/index',
    'pages/record/rate/index',
    'pages/record/select/index',
    'pages/record/cascader/index',
    'pages/record/switch/index',
    'pages/record/textarea/index',
    'pages/record/upload-image/index',
    'pages/callback/alert/index',
    'pages/callback/drawer/index',
    'pages/callback/loading/index',
    'pages/callback/modal/index',
    'pages/callback/progress/index',
    'pages/data/carousel/index',
    'pages/data/collapse/index',
    'pages/data/count-down/index',
    'pages/data/table/index',
    'pages/data/tabs/index',
    'pages/data/tag/index',
    'pages/data/badge/index',
    'pages/data/date-picker/index',
    'pages/other/back-top/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: '千牛UI 组件库',
    navigationBarTextStyle: 'black',
  },
};
